import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen bg-black text-white flex flex-col">
      <Head>
        <title>Terms of Service - Bridge</title>
        <meta name="description" content="Terms of Service for Bridge" />
        <link rel="icon" href="/images/bridge.svg" />
      </Head>

      <Header />

      <main className="flex-grow px-4 sm:px-6 lg:px-8 py-16">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-ocr-a mb-8">Terms of Service</h1>
          
          <div className="space-y-8 font-jetbrains-mono text-gray-300">
            <section>
              <h2 className="text-xl text-white mb-4">Acceptance of Terms</h2>
              <p>
                By accessing or using Bridge, including our CLI tool and website, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.
              </p>
            </section>

            <section>
              <h2 className="text-xl text-white mb-4">Description of Service</h2>
              <p>
                Bridge provides a CLI tool for managing dependency updates in software projects. The tool analyzes your local repository, identifies safe patch and minor updates, validates them using your existing test suite, and creates pull requests with evidence of successful validation.
              </p>
            </section>

            <section>
              <h2 className="text-xl text-white mb-4">Use of the CLI</h2>
              <p className="mb-4">
                The Bridge CLI is provided "as is" for use in your software development workflow. You are responsible for reviewing all changes and pull requests generated by the tool before merging them into your codebase.
              </p>
              <p>
                You agree not to use Bridge in any way that violates applicable laws or regulations, or to attempt to interfere with the proper functioning of the service.
              </p>
            </section>

            <section>
              <h2 className="text-xl text-white mb-4">Intellectual Property</h2>
              <p>
                Bridge and its original content, features, and functionality are owned by Bridge and are protected by applicable intellectual property laws. Your use of Bridge does not grant you ownership of any intellectual property rights in our services.
              </p>
            </section>

            <section>
              <h2 className="text-xl text-white mb-4">Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, Bridge shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service, including any damages arising from dependency updates or code changes.
              </p>
            </section>

            <section>
              <h2 className="text-xl text-white mb-4">Changes to Terms</h2>
              <p>
                We reserve the right to modify these terms at any time. Continued use of Bridge after changes constitutes acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl text-white mb-4">Contact</h2>
              <p>
                For questions about these Terms, please contact us through our <a href="/contact" className="text-green-400 hover:underline">contact page</a>.
              </p>
            </section>

            <section className="text-sm text-gray-500">
              <p>Last updated: March 2026</p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
